### ISSUE TITLE
Errors building

### ISSUE THREAD

**Issue by leeuwenrjj** [avinetworks/terraform-provider-avi#64]
Hello, I have issues building the binary.
It looks like something changed in the terraform code so it no longer builds?

# make build
==> Checking that code complies with gofmt requirements...
go install
# _/src/github.com/hashicorp/terraform-provider-avi
./main.go:10:15: cannot use avi.Provider (type func() "github.com/avinetworks/terraform-provider-avi/vendor/github.com/hashicorp/terraform/terraform".ResourceProvider) as type "github.com/hashicorp/terraform/plugin".ProviderFunc in field value
make: *** [build] Error 2

**Comment by grastogi23** [comment]
we will try this out..

**Comment by grastogi23** [comment]
@leeuwenrjj  it did build fine for me with latest terraform source. Also, can you please put the avi provider in 
src/github.com/**avinetworks**/terraform-provider-avi

It is possible that is failing for you. We had to change the reference to make test acceptance pass.

**Comment by leeuwenrjj** [comment]
Thx! That helped.
Can we update the README for that?

**Comment by leeuwenrjj** [comment]
Also, before the build you will need to do a "go get"

**Comment by grastogi23** [comment]
Yes we will do that.  Thanks.

Gaurav Rastogi
Avi Networks


On Jul 19, 2018, at 7:02 AM, leeuwenrjj <notifications@github.com> wrote:

Thx! That helped.
Can we update the README for that?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/avinetworks/terraform-provider-avi/issues/64#issuecomment-406286998>,
or mute the thread
